# -*- coding: utf-8 -*-
"""Train package: session assembly, cost, optimization, parameter schema, implementation, and cli.

Public facade re-exporting train API names (``import train``). Engine internals are split across
:mod:`train.param`, :mod:`train.session`, :mod:`train.cost`, :mod:`train.optimization`,
:mod:`train.implementation`, :mod:`train.cli`; the shared vocabulary lives in
:mod:`train.config`. Numeric defaults live in :mod:`default_params`. Lower layers
(``neuron``, ``task``, ``network``) never import this package at load time.
"""
from __future__ import annotations

from default_params import (
    ANALYZE_CELL_DYNAMICS,
    MODEL,
    MOVING_BAR_INPUT,
    NEURON_FORWARD,
    NEURON_PARAM,
    NEURON_SCHEMA,
    NETWORK_CONSTRUCTION,
    NETWORK_PATH,
    SPOT_INPUT,
    SPOT_PACK,
    STI_TIMING,
    TRAIN_CONFIG,
    TRAIN_OPTIMIZATION,
    TRAIN_OPTS,
    TRAIN_SESSION,
)

from neuron import (
    SEGMENT_NAMES,
    EULER_CLI,
    EULER_MODES,
    I_H_SHAPE_SEGMENT_NAMES,
    KNOWN_MODELS,
    SYN_MODES,
    build_schema,
    e_h_rev,
    expand_euler,
    membrane_dt_over_c,
    t_from_ms,
    t_abs_from_ms,
    normalize_syn_mode,
    ca_from_v_ca,
    forward_ca,
    forward_full,
    forward_nodes,
    forward_v,
    pack_t_onset,
    step_delta_ms,
    ms_from_t,
    update_state_hp_lp,
    update_v,
    v_ca_from_v,
    v_component_from_g,
)

from train.config import (
    CLI_TASK_NAMES,
    COST_NORMS,
    SPOT_GT_MODES,
    MOVING_BAR_TASKS,
    PD_ND_LABELS,
    SPOT_TASKS,
    TASK_ALIASES,
    TRAIN_OPTS_FILE,
    VALID_TASKS,
    cost_part_keys_for_task,
    expand_cost_norm,
    expand_part_cost_scale_dict,
    expand_filter,
    expand_spot_gt_mode,
    expand_gt_dict,
    expand_pre_steady,
    expand_tasks,
    moving_bar_cost_part_key,
    resolve_tasks,
    resolve_cost_radius_by_task,
    session_cost_part_keys,
)
from train.param import (
    PAIR_SEP,
    PARAM_MODES,
    ModelBackend,
    SIM_DTYPE,
    active_device,
    override_param_modes,
    assign_params,
    attach_param_carry,
    inits_from_param_by_segment,
    build_i_h_dirs,
    calc_multi_col_params,
    edges_for_backend,
    guess_initial_params,
    z_moments_from_param_by_segment,
    pairs_for_backend,
    params_from_z,
    parse_param_mode_text,
    parse_param_cli,
    parse_optimizable_param_tokens,
    override_param_inits,
    override_params,
    remap_param_by_segment_moments,
    remap_param_by_segment_node_values,
    override_val_from,
    bias_gt_from_onset_trace,
    parse_val_from_tokens,
    resolve_val_from,
    val_from_enabled,
    resolve_param_modes,
    schema_bounds,
    schema_guess,
    schema_nparams,
    schema_param_modes_record,
    segment_n_z,
    cells_for_backend,
    slots_for_segment,
    z_from_node_values,
    validate_syn_strength_edge_param_mode,
    moments_by_segment_from_z,
    node_values_from_z,
    sim_dtype_from_fp,
)
from train.session import (
    NETWORK_TASK_BUILDERS,
    Pack,
    TrainSession,
    _cost_radius_hex_coltag,
    override_pack,
    override_i_sti,
    resolve_i_sti_paradigm,
    extend_pack_mirror_fit,
    load_network_backend,
    resolve_train_opts,
    open_session,
    resolve_session,
    session_from_outdir,
    resolve_gt_cells_by_task,
    resolve_cell_indices,
)
from train.cost import (
    FusedForward,
    calc_cost,
    calc_cost_parts,
    gt_affine_for_nodes,
    pack_cost_abs_time_idx,
)
from train.optimization import (
    TrainResult,
    adam_moments_from_state_dict,
    do_many_runs,
    gradient_network,
    optimize_staged,
)

from task.spot.pack import build_spot_sti_opts
from task.moving_bar.pack import build_moving_bar_sti_opts, session_moving_bar_i_baseline
