"""
神经元简化工具 - 保留物理性质的版本
支持输出Jaxley兼容的SWC格式

作者: Claude
日期: 2026-04-08
"""

import os
import math
import json
import numpy as np
from typing import Dict, List, Tuple, Optional
from dataclasses import dataclass, asdict


@dataclass
class SimplificationStats:
    """简化统计信息"""
    original_nodes: int
    simplified_nodes: int
    removed_by_collinear: int
    removed_by_pruning: int
    total_surface_area_original: float
    total_surface_area_simplified: float
    surface_area_preservation_ratio: float
    angle_threshold: float
    keep_ratio: float


class NeuronSimplifier:
    """神经元简化器 - 保留物理性质"""
    
    def __init__(self, angle_threshold_degrees: float = 5.0, 
                 min_segment_length: float = 1e-6):
        """
        初始化简化器
        
        Args:
            angle_threshold_degrees: 共线判断的角度阈值（度）
            min_segment_length: 最小段长度阈值
        """
        self.angle_threshold = angle_threshold_degrees
        self.min_segment_length = min_segment_length
        
    def load_swc(self, filepath: str) -> Tuple[Dict, int]:
        """
        加载SWC文件
        
        Args:
            filepath: SWC文件路径
            
        Returns:
            (nodes, root): 节点字典和根节点ID
        """
        nodes = {}
        with open(filepath) as f:
            for line in f:
                if line.startswith("#") or len(line.strip()) == 0:
                    continue
                parts = line.strip().split()
                if len(parts) < 7:
                    continue
                    
                nid = int(parts[0])
                pid = int(parts[6])
                nodes[nid] = {
                    "id": nid,
                    "type": int(parts[1]),
                    "x": float(parts[2]),
                    "y": float(parts[3]),
                    "z": float(parts[4]),
                    "r": float(parts[5]),
                    "parent": pid,
                    "children": []
                }
        
        # 构建children关系
        for nid, node in nodes.items():
            pid = node["parent"]
            if pid != -1 and pid in nodes:
                nodes[pid]["children"].append(nid)
        
        # 找到根节点
        root = [nid for nid, node in nodes.items() if node["parent"] == -1][0]
        return nodes, root
    
    def write_swc(self, nodes: Dict, out_path: str):
        """
        写入SWC文件（Jaxley兼容格式）
        
        Jaxley's `to_swc_graph` uses `np.loadtxt` which requires:
        - 7 numeric columns: id type x y z radius parent
        - IDs should be integers (but need NOT be contiguous)
        - `#` lines are skipped as comments
        
        Potential issues fixed here:
        1. Renumber IDs starting from 1 (Jaxley's `_add_missing_graph_attrs`
           accesses `graph.nodes[1]` which will KeyError if node 1 is missing).
        2. Ensure exactly one root (parent=-1). Jaxley assumes a single tree.
        
        Args:
            nodes: 节点字典
            out_path: 输出文件路径
        """
        # Ensure single root: connect extra roots to the first one
        roots = [nid for nid, n in nodes.items() if n['parent'] == -1]
        if len(roots) > 1:
            main_root = roots[0]
            for extra_root in roots[1:]:
                nodes[extra_root]['parent'] = main_root
        
        # Renumber IDs from 1 so Jaxley's graph.nodes[1] always exists
        old_ids = sorted(nodes.keys())
        id_map = {old: new for new, old in enumerate(old_ids, start=1)}
        
        with open(out_path, 'w') as f:
            f.write("# Simplified neuron morphology\n")
            f.write("# Generated by NeuronSimplifier with physics preservation\n")
            f.write("# Format: id type x y z radius parent\n")
            
            for old_id in old_ids:
                n = nodes[old_id]
                new_id = id_map[old_id]
                new_parent = id_map[n['parent']] if n['parent'] != -1 and n['parent'] in id_map else -1
                f.write(f"{new_id} {n['type']} {n['x']:.6f} {n['y']:.6f} "
                       f"{n['z']:.6f} {n['r']:.6f} {new_parent}\n")
    
    def compute_distance(self, node1: Dict, node2: Dict) -> float:
        """计算两个节点之间的欧氏距离"""
        dx = node1['x'] - node2['x']
        dy = node1['y'] - node2['y']
        dz = node1['z'] - node2['z']
        return math.sqrt(dx*dx + dy*dy + dz*dz)
    
    def compute_surface_area(self, nodes: Dict) -> float:
        """
        计算神经元的总表面积
        
        使用圆柱体表面积公式: A = 2πrL
        """
        total_area = 0.0
        for nid, node in nodes.items():
            pid = node['parent']
            if pid != -1 and pid in nodes:
                length = self.compute_distance(node, nodes[pid])
                radius = node['r']
                area = 2 * math.pi * radius * length
                total_area += area
        return total_area
    
    def simplify_collinear_nodes(self, nodes: Dict) -> Tuple[Dict, int]:
        """
        移除共线节点，同时保留物理性质（表面积、电容）
        
        核心改进：
        1. 计算合并后的等效半径，保留总表面积
        2. 使用长度加权平均: r_eq = (r1*L1 + r2*L2) / (L1 + L2)
        
        Args:
            nodes: 节点字典
            
        Returns:
            (simplified_nodes, removed_count): 简化后的节点和删除数量
        """
        removed_total = 0
        candidates_total = 0
        
        while True:
            # 构建children字典
            children = {nid: [] for nid in nodes}
            for nid in nodes:
                pid = nodes[nid]['parent']
                if pid != -1 and pid in nodes:
                    children[pid].append(nid)
            
            removed_any = False
            
            for nid in list(nodes.keys()):
                if nid not in nodes:
                    continue
                    
                node = nodes[nid]
                pid = node['parent']
                
                # 检查是否可以合并
                if pid == -1 or pid not in nodes:
                    continue
                    
                child_list = children.get(nid, [])
                if len(child_list) != 1:
                    continue
                    
                cid = child_list[0]
                if cid not in nodes:
                    continue
                
                # 计算角度
                p = np.array([nodes[pid]['x'], nodes[pid]['y'], nodes[pid]['z']])
                a = np.array([node['x'], node['y'], node['z']])
                c = np.array([nodes[cid]['x'], nodes[cid]['y'], nodes[cid]['z']])
                
                v1 = p - a  # parent -> node
                v2 = c - a  # node -> child
                
                len1 = np.linalg.norm(v1)
                len2 = np.linalg.norm(v2)
                
                if len1 < self.min_segment_length or len2 < self.min_segment_length:
                    continue
                
                candidates_total += 1
                
                # 判断是否共线
                cos_angle = np.dot(v1, v2) / (len1 * len2)
                cos_angle = max(-1.0, min(1.0, cos_angle))
                cos_limit = -math.cos(math.radians(self.angle_threshold))
                
                if cos_angle <= cos_limit:
                    # 共线：合并节点，保留物理性质
                    
                    # 计算等效半径（保留表面积）
                    r1 = nodes[pid]['r']
                    r2 = node['r']
                    L1 = len1
                    L2 = len2
                    
                    # 长度加权平均半径
                    r_eq = (r1 * L1 + r2 * L2) / (L1 + L2)
                    
                    # 更新子节点
                    nodes[cid]['parent'] = pid
                    nodes[cid]['r'] = r_eq  # 使用等效半径
                    
                    # 删除中间节点
                    del nodes[nid]
                    removed_any = True
                    removed_total += 1
            
            if not removed_any:
                break
        
        print(f"[Collinear] Candidates={candidates_total}, Removed={removed_total}, "
              f"Angle≤{self.angle_threshold}°")
        
        return nodes, removed_total
    
    def compute_distances(self, nodes: Dict, root: int) -> Dict[int, float]:
        """计算每个节点到根节点的累积距离 g(v)"""
        dist = {root: 0.0}
        stack = [root]
        
        while stack:
            nid = stack.pop()
            parent_dist = dist[nid]
            
            for cid in nodes[nid]["children"]:
                if cid not in nodes:
                    continue
                    
                edge_length = self.compute_distance(nodes[nid], nodes[cid])
                dist[cid] = parent_dist + edge_length
                stack.append(cid)
        
        return dist
    
    def compute_max_subtree_dist(self, nodes: Dict, root: int, 
                                 dist: Dict[int, float]) -> Dict[int, float]:
        """计算每个节点子树的最大g(v)值"""
        max_dist = {}
        
        def dfs(nid):
            m = dist.get(nid, 0.0)
            for cid in nodes[nid]["children"]:
                if cid in nodes and cid in dist:
                    m = max(m, dfs(cid))
            max_dist[nid] = m
            return m
        
        dfs(root)
        return max_dist
    
    def compute_branch_persistence(self, nodes: Dict, root: int,
                                   dist: Dict[int, float],
                                   max_dist: Dict[int, float]) -> List[Tuple[int, int, float]]:
        """
        计算每条叶分支的持久值
        
        Returns:
            List of (leaf_id, split_point_id, persistence)
        """
        branches = []
        
        for nid, node in nodes.items():
            if len(node["children"]) == 0:  # leaf
                leaf = nid
                current = leaf
                
                while True:
                    parent = nodes[current]["parent"]
                    
                    if parent == -1:
                        s = parent
                        break
                    
                    if parent not in nodes:
                        s = -1
                        break
                    
                    # 检查兄弟节点
                    siblings = [c for c in nodes[parent]["children"] 
                               if c != current and c in nodes and c in max_dist]
                    
                    if any(max_dist.get(sib, 0) > dist.get(leaf, 0) for sib in siblings):
                        s = parent
                        break
                    
                    current = parent
                
                persistence = dist.get(leaf, 0) - dist.get(s, 0)
                branches.append((leaf, s, persistence))
        
        # 按持久值降序排序
        branches.sort(key=lambda x: -x[2])
        return branches
    
    def prune_tree(self, nodes: Dict, branches: List[Tuple[int, int, float]],
                   keep_ratio: float) -> Tuple[Dict, int]:
        """
        基于持久性剪枝
        
        Args:
            nodes: 节点字典
            branches: 分支列表 (leaf, split_point, persistence)
            keep_ratio: 保留的分支比例
            
        Returns:
            (pruned_nodes, removed_count): 剪枝后的节点和删除数量
        """
        keep_set = set()
        n_keep = max(1, int(len(branches) * keep_ratio))
        kept = branches[:n_keep]
        
        # 保留选中分支的所有节点
        for leaf, s, _ in kept:
            current = leaf
            while current != s and current != -1:
                keep_set.add(current)
                if current not in nodes:
                    break
                current = nodes[current]["parent"]
            if s != -1:
                keep_set.add(s)
        
        # 添加根节点
        root_nodes = [nid for nid, node in nodes.items() if node["parent"] == -1]
        if root_nodes:
            keep_set.add(root_nodes[0])
        
        # 创建新的节点字典
        original_count = len(nodes)
        new_nodes = {nid: node.copy() for nid, node in nodes.items() if nid in keep_set}
        
        # 清理parent和children关系
        for nid in list(new_nodes):
            node = new_nodes[nid]
            pid = node["parent"]
            if pid not in new_nodes:
                node["parent"] = -1
            node["children"] = [cid for cid in node["children"] if cid in new_nodes]
        
        removed_count = original_count - len(new_nodes)
        return new_nodes, removed_count
    
    def simplify(self, nodes: Dict, root: int, keep_ratio: float = 1.0) -> Tuple[Dict, SimplificationStats]:
        """
        完整的简化流程
        
        Args:
            nodes: 原始节点字典
            root: 根节点ID
            keep_ratio: 保留的分支比例（0-1）
            
        Returns:
            (simplified_nodes, stats): 简化后的节点和统计信息
        """
        original_nodes = nodes.copy()
        original_count = len(nodes)
        original_area = self.compute_surface_area(nodes)
        
        # 步骤1: 共线节点合并
        print(f"Original nodes: {original_count}")
        nodes, removed_collinear = self.simplify_collinear_nodes(nodes)
        print(f"After collinear removal: {len(nodes)} (removed {removed_collinear})")
        
        # 步骤2: 基于持久性的剪枝
        if keep_ratio < 1.0:
            dist = self.compute_distances(nodes, root)
            max_dist = self.compute_max_subtree_dist(nodes, root, dist)
            branches = self.compute_branch_persistence(nodes, root, dist, max_dist)
            nodes, removed_pruning = self.prune_tree(nodes, branches, keep_ratio)
            print(f"After pruning (ratio={keep_ratio}): {len(nodes)} (removed {removed_pruning})")
        else:
            removed_pruning = 0
        
        # 计算统计信息
        simplified_area = self.compute_surface_area(nodes)
        stats = SimplificationStats(
            original_nodes=original_count,
            simplified_nodes=len(nodes),
            removed_by_collinear=removed_collinear,
            removed_by_pruning=removed_pruning,
            total_surface_area_original=original_area,
            total_surface_area_simplified=simplified_area,
            surface_area_preservation_ratio=simplified_area / original_area if original_area > 0 else 0,
            angle_threshold=self.angle_threshold,
            keep_ratio=keep_ratio
        )
        
        return nodes, stats
    
    def save_metadata(self, stats: SimplificationStats, original_file: str, 
                     output_file: str):
        """保存简化元数据到JSON文件"""
        metadata = {
            "original_file": original_file,
            "output_file": output_file,
            "simplification_params": {
                "angle_threshold_degrees": stats.angle_threshold,
                "keep_ratio": stats.keep_ratio
            },
            "statistics": asdict(stats)
        }
        
        json_path = output_file.replace('.swc', '_metadata.json')
        with open(json_path, 'w') as f:
            json.dump(metadata, f, indent=2)
        
        print(f"Metadata saved to: {json_path}")


def main():
    """示例用法"""
    # 创建简化器
    simplifier = NeuronSimplifier(angle_threshold_degrees=5.0)
    
    # 加载SWC文件
    input_file = "/path/to/neuron.swc"
    nodes, root = simplifier.load_swc(input_file)
    
    # 简化（保留50%的分支）
    simplified_nodes, stats = simplifier.simplify(nodes, root, keep_ratio=0.5)
    
    # 保存结果
    output_file = "/path/to/neuron_simplified.swc"
    simplifier.write_swc(simplified_nodes, output_file)
    simplifier.save_metadata(stats, input_file, output_file)
    
    # 打印统计信息
    print(f"\n=== Simplification Results ===")
    print(f"Original nodes: {stats.original_nodes}")
    print(f"Simplified nodes: {stats.simplified_nodes}")
    print(f"Reduction: {(1 - stats.simplified_nodes/stats.original_nodes)*100:.1f}%")
    print(f"Surface area preservation: {stats.surface_area_preservation_ratio*100:.1f}%")


if __name__ == "__main__":
    main()
